//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRpaService")]
public interface IRpaService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRpaService/SendMessage", ReplyAction="http://tempuri.org/IRpaService/SendMessageResponse")]
    string SendMessage(string message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRpaService/SendMessage", ReplyAction="http://tempuri.org/IRpaService/SendMessageResponse")]
    System.Threading.Tasks.Task<string> SendMessageAsync(string message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRpaService/ReciveMessage", ReplyAction="http://tempuri.org/IRpaService/ReciveMessageResponse")]
    string[] ReciveMessage();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRpaService/ReciveMessage", ReplyAction="http://tempuri.org/IRpaService/ReciveMessageResponse")]
    System.Threading.Tasks.Task<string[]> ReciveMessageAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRpaService/ClearQueue", ReplyAction="http://tempuri.org/IRpaService/ClearQueueResponse")]
    void ClearQueue();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRpaService/ClearQueue", ReplyAction="http://tempuri.org/IRpaService/ClearQueueResponse")]
    System.Threading.Tasks.Task ClearQueueAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRpaService/GetActiveTabFilePath", ReplyAction="http://tempuri.org/IRpaService/GetActiveTabFilePathResponse")]
    string GetActiveTabFilePath();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRpaService/GetActiveTabFilePath", ReplyAction="http://tempuri.org/IRpaService/GetActiveTabFilePathResponse")]
    System.Threading.Tasks.Task<string> GetActiveTabFilePathAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRpaServiceChannel : IRpaService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RpaServiceClient : System.ServiceModel.ClientBase<IRpaService>, IRpaService
{
    
    public RpaServiceClient()
    {
    }
    
    public RpaServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RpaServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RpaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RpaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string SendMessage(string message)
    {
        return base.Channel.SendMessage(message);
    }
    
    public System.Threading.Tasks.Task<string> SendMessageAsync(string message)
    {
        return base.Channel.SendMessageAsync(message);
    }
    
    public string[] ReciveMessage()
    {
        return base.Channel.ReciveMessage();
    }
    
    public System.Threading.Tasks.Task<string[]> ReciveMessageAsync()
    {
        return base.Channel.ReciveMessageAsync();
    }
    
    public void ClearQueue()
    {
        base.Channel.ClearQueue();
    }
    
    public System.Threading.Tasks.Task ClearQueueAsync()
    {
        return base.Channel.ClearQueueAsync();
    }
    
    public string GetActiveTabFilePath()
    {
        return base.Channel.GetActiveTabFilePath();
    }
    
    public System.Threading.Tasks.Task<string> GetActiveTabFilePathAsync()
    {
        return base.Channel.GetActiveTabFilePathAsync();
    }
}
