//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GettingStartedClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRpaService")]
    public interface IRpaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRpaService/GetData", ReplyAction="http://tempuri.org/IRpaService/GetDataResponse")]
        string GetData(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRpaService/GetData", ReplyAction="http://tempuri.org/IRpaService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRpaService/ShowData", ReplyAction="http://tempuri.org/IRpaService/ShowDataResponse")]
        string ShowData(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRpaService/ShowData", ReplyAction="http://tempuri.org/IRpaService/ShowDataResponse")]
        System.Threading.Tasks.Task<string> ShowDataAsync(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRpaServiceChannel : GettingStartedClient.ServiceReference1.IRpaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RpaServiceClient : System.ServiceModel.ClientBase<GettingStartedClient.ServiceReference1.IRpaService>, GettingStartedClient.ServiceReference1.IRpaService {
        
        public RpaServiceClient() {
        }
        
        public RpaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RpaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RpaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RpaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(string message) {
            return base.Channel.GetData(message);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string message) {
            return base.Channel.GetDataAsync(message);
        }
        
        public string ShowData(string message) {
            return base.Channel.ShowData(message);
        }
        
        public System.Threading.Tasks.Task<string> ShowDataAsync(string message) {
            return base.Channel.ShowDataAsync(message);
        }
    }
}
